
#### SEND REQUEST TO GETS A PROFILE
GET http://localhost:4000/api/v1/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODk5MzIwNi0wYTljLTRiNmQtODQ1NS1mMWQxMDA3N2RmMjYiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiYXlvbWlkZXNoZXJpZjIwMTlAZ21haWwuY29tIiwiaWF0IjoxNzQ4MjY0MDc1LCJleHAiOjE3NDg1MjMyNzV9.9m4Od6lC0QNe4B77tzOblHppXX3rcK4S2DUPe_ZLvZk

#### SEND REQUEST TO GETS A PROFILE
POST http://localhost:4000/api/v1/auth/verify-email
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb2RlIjo1Mjc5MzYsImlkIjoiZWRiNDNlMTMtYjE1OS00Y2FlLTk0ZDYtMDRlYTA3YTg3NTU0IiwibmFtZSI6IkFtb2R1IG1vbGxlciIsImVtYWlsIjoiYXlvbWlkZXNoZXJpZjIwMTlAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDgyMDAxNTksImV4cCI6MTc0ODIwMzc1OX0.JBo93sau4xZik3GFKoy__6axtG228iQKD0VH4jSxfIo
Content-Type: application/json

{
  "verification_code": "581195"
}

#### LOG OUT USER
POST http://localhost:4000/api/v1/user/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODk5MzIwNi0wYTljLTRiNmQtODQ1NS1mMWQxMDA3N2RmMjYiLCJyb2xlIjoidXNlciIsImVtYWlsIjoiYXlvbWlkZXNoZXJpZjIwMTlAZ21haWwuY29tIiwiaWF0IjoxNzQ4MjY0MDc1LCJleHAiOjE3NDg1MjMyNzV9.9m4Od6lC0QNe4B77tzOblHppXX3rcK4S2DUPe_ZLvZk



#### LOGIN A USER
POST http://localhost:4000/api/v1/auth/login
Content-Type: application/json

{
  "email": "ayomidesherif2019@gmail.com",
  "password": "Test123#@"
}

#### CREATE A NEW User
POST http://localhost:4000/api/v1/auth/register
Content-Type: application/json

{
  "name": "Amodu moller",
  "email": "ayomidesherif2019@gmail.com",
  "password": "Test123#@"
}

#### CREATE A NEW User
DELETE  http://localhost:9200/songs
Content-Type: application/json


#### SEND REQUEST TO FORGOT PASSWORD
POST http://localhost:8080/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "ayomidesherif2019@gmail.com"
}


#### SEND REQUEST TO RESEND VERIFICATION EMAIL CODE
GET http://localhost:8080/api/v1/auth/resend-email-code
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5b21pZGVzaGVyaWYyMDE5QGdtYWlsLmNvbSIsImlhdCI6MTc0MjY4NTAxNCwiZXhwIjoxNzQyOTQ0MjE0fQ.JqTjd-y6mJXexJT7RuC1xgAU-9ZY5hYVqqkaXeiPyUI


#### SEND REQUEST TO VERIFY FORGOT PASSWORD CODE
POST  http://localhost:8080/api/v1/auth/forgot-password-code
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5b21pZGVzaGVyaWYyMDE5QGdtYWlsLmNvbSIsImlhdCI6MTc0MjY4NTAxNCwiZXhwIjoxNzQyOTQ0MjE0fQ.JqTjd-y6mJXexJT7RuC1xgAU-9ZY5hYVqqkaXeiPyUI

{
  "verificationCode": "332161"
}

#### SEND REQUEST TO RESET PASSWORD
PATCH http://localhost:8080/api/v1/auth/reset-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF5b21pZGVzaGVyaWYyMDE5QGdtYWlsLmNvbSIsImlhdCI6MTc0MjY4NTAxNCwiZXhwIjoxNzQyOTQ0MjE0fQ.JqTjd-y6mJXexJT7RuC1xgAU-9ZY5hYVqqkaXeiPyUI

{
  "new_password": "Testing26377#!@",
  "confirm_newpassword": "Testing26377#!@"
}